import datetime

today = datetime.datetime.today()
tommorow = today + datetime.timedelta(days=1)
dayAfterTommorow = tommorow + datetime.timedelta(days = 1)

todayStr = today.strftime("%m/%d/%Y %H:%M")
tommorowStr = tommorow.strftime("%m/%d/%Y %H:%M")
dayAfterTommorowStr = dayAfterTommorow.strftime("%m/%d/%Y %H:%M")

#print(todayStr)
#print(tommorowStr)
#print(dayAfterTommorowStr)

cities = ["Novi Sad", "Belgrade", "Nis"]
#tours.txt
#                                              max at|current|remaining cap|duration ... |guideid
#0|Visit to Novi Sad|NOT_STARTED|Beutiful!|Serbian|8|8|0|2|4/3/2023 12:00:00 AM|21|0 #location id

#locations.txt
#0|||Novi Sad|Serbia
#1|||Belgrade|Serbia
#2|||Nis|Serbia

tours = open("tours.txt","w")
locationid = 0
id = 0
for city in cities:
    tours.write(str(id) + "|Visit to " +city+ " vol. " + str(locationid) + "|NOT_STARTED" + "|Autogenerated" + "|Serbian" + "|10|0|10|"+str(locationid+1)+"|"+todayStr+"|21|"+str(locationid)+"\n")
    id+=1
    tours.write(str(id) + "|Visit to " +city+ " vol. " + str(locationid) + "|NOT_STARTED" + "|Autogenerated" + "|Chinese" + "|10|0|10|"+str(locationid+1)+"|"+tommorowStr+"|21|"+str(locationid)+"\n")
    id+=1
    tours.write(str(id) + "|Visit to " +city+ " vol. " + str(locationid) + "|NOT_STARTED" + "|Autogenerated" + "|Spanish" + "|10|0|10|"+str(locationid+1)+"|"+dayAfterTommorowStr+"|21|"+str(locationid)+"\n")
    id+=1 
    locationid+=1   
tours.close()

tourcheckpoints = open("tourcheckpoints.txt","w")
for i in range(9):
    if i < 3:
        tourcheckpoints.write(str(i)+"|0|False\n")
        tourcheckpoints.write(str(i)+"|1|False\n")
        tourcheckpoints.write(str(i)+"|2|False\n")            
    elif i < 6:
        tourcheckpoints.write(str(i)+"|3|False\n")
        tourcheckpoints.write(str(i)+"|4|False\n")
        tourcheckpoints.write(str(i)+"|5|False\n")
    else:
        tourcheckpoints.write(str(i)+"|6|False\n")
        tourcheckpoints.write(str(i)+"|7|False\n")
        tourcheckpoints.write(str(i)+"|8|False\n")                        
tourcheckpoints.close()       
#checkpoints.txt
'''
0|Miletic|0
1|Dunavski|0
2|Petrovaradin|0
3|Hram Svetog Save|1
4|Kalemegdan|1
5|Knez Mihajlova ulica|1
6|Niska tvrdjava|2
7|Cele kula|2
8|Park Cair|2
'''

tourtouristcheckpoint = open("tourtouristcheckpoint.txt", "w")
tourtouristcheckpoint.close()

tourtourist = open("tourtourist.txt", "w")
tourtourist.close()